version: "3.8"

services:
  django_app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ./:/workspace
      - ./storage:/workspace/storage
    ports:
      - 8001:8001
    env_file:
      - ./.env
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - mysql_db
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql_db:
    image: mariadb:10.11
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_mysql_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    #networks:
      #- app-mysql-phpmyadmin

  phpmyadmin:
    depends_on:
      - mysql_db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: mysql_db
      MYSQL_ROOT_PASSWORD: root
    #networks:
      #- app-mysql-phpmyadmin

#networks:
  #app-mysql-phpmyadmin:

volumes:
  db_data:
